### ISSUE TITLE
Bug with double letters

### ISSUE THREAD

**Issue by Christoph142** [HeySreelal/xwordle#97]
Today's word (06.07. - sorry, don't want to spoil anyone) returned 🟢🟢⚫🟡⚫ for "doors". IINM it should be 🟢🟢🟡🟡⚫ instead.

**Comment by HeySreelal** [comment]
Heyy! Thanks for reporting! I'll quickly check this one :)

**Comment by HeySreelal** [comment]
Hey again, confirming that was a bug - and it should be fixed by now :) 

Thank you so much for reporting it, and apart from that I'm super happy to see you playing!

**Comment by HeySreelal** [comment]
We actually have a cool new feature drop today along with this release. Namely, in game Hints - a detailed release note will be sent out soon. 

If you may, please send me your Telegram ID through `/feedback` (in case you want to share it privately) - I'd love to send some free hints to you as a token of appreciation.

Good luck, happy gaming! 🎮
